### ISSUE TITLE
Use port forwarding instead of External IPs

### ISSUE THREAD

**Issue by lukeoguro** [team-aglr/edemame#28]
External IPs (Load balancers) will force us to use authentication for the **DB API** and **Grafana server**. Investigate if port forwarding is appropriate for our use case, and make the switch.

**Comment by lukeoguro** [comment]
Make sure to check #19, @westrachel mentions a few important considerations.

**Comment by westrachel** [comment]
goals for updating grafana:
i. Update edamame init command to return port forward version of the grafana dashboard (localhost:GRAF_PORT) instead of external ip
ii. Update run test to give user more specific port forward grafana dashboard path that includes query parameters that includes their specific testid

**Comment by elguaposalsero** [comment]
iii. Also would be nice if we could default to a specific dashboard (e.g. http-data) and a specific time period (e.g. last 15 minutes). Here's the URL I get for a specific test:

http://ac4539c0cd701470bb0e6062d30d4e97-938015919.us-west-1.elb.amazonaws.com:3000/d/IWSghv-4k/http-data?orgId=1&refresh=5s&from=now-15m&to=now

@westrachel

**Comment by westrachel** [comment]
The url that I'm working off of is like this: http://a0f5facb5d64f42ba8eab7c57e2e5875-782175933.us-west-1.elb.amazonaws.com:3000/d/IWSghv-4k/http-data?orgId=1&var-testid=27&from=now-5m&to=now&refresh=5s, but I'll switch to last 15 minutes
